/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.Daybalance

import com.squareup.moshi.Json
/**
 * 
 * @param status 
 * @param balance 
 */

data class Balance (
    @Json(name = "status")
    val status: kotlin.String? = null,
    @Json(name = "balance")
    val balance: Daybalance? = null
) 



