/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.DirectionsMatrixSources

import com.squareup.moshi.Json
/**
 * 
 * @param code 
 * @param distances 
 * @param fallbackSpeedCells 
 * @param sources 
 * @param destinations 
 */

data class DirectionsMinusMatrix (
    @Json(name = "code")
    val code: kotlin.String? = null,
    @Json(name = "distances")
    val distances: kotlin.Array<java.math.BigDecimal>? = null,
    @Json(name = "fallback_speed_cells")
    val fallbackSpeedCells: kotlin.Array<java.math.BigDecimal>? = null,
    @Json(name = "sources")
    val sources: kotlin.Array<DirectionsMatrixSources>? = null,
    @Json(name = "destinations")
    val destinations: kotlin.Array<DirectionsMatrixSources>? = null
) 



