/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.DirectionsDirectionsRoutes

import com.squareup.moshi.Json
/**
 * 
 * @param code 
 * @param waypoints 
 * @param routes 
 */

data class DirectionsMinusDirections (
    @Json(name = "code")
    val code: kotlin.String? = null,
    @Json(name = "waypoints")
    val waypoints: kotlin.Array<kotlin.Any>? = null,
    @Json(name = "routes")
    val routes: kotlin.Array<DirectionsDirectionsRoutes>? = null
) 



