/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package locationiq.models


import com.squareup.moshi.Json
/**
 * 
 * @param legs 
 * @param weightName 
 * @param geometry 
 * @param weight 
 * @param distance 
 * @param duration 
 */

data class DirectionsDirectionsRoutes (
    @Json(name = "legs")
    val legs: kotlin.Array<kotlin.Any>? = null,
    @Json(name = "weight_name")
    val weightName: kotlin.String? = null,
    @Json(name = "geometry")
    val geometry: kotlin.String? = null,
    @Json(name = "weight")
    val weight: java.math.BigDecimal? = null,
    @Json(name = "distance")
    val distance: java.math.BigDecimal? = null,
    @Json(name = "duration")
    val duration: java.math.BigDecimal? = null
) 



