/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package locationiq.models

import locationiq.models.DirectionsNearestWaypoints

import com.squareup.moshi.Json
/**
 * 
 * @param code 
 * @param waypoints 
 */

data class DirectionsMinusNearest (
    @Json(name = "code")
    val code: kotlin.String? = null,
    @Json(name = "waypoints")
    val waypoints: kotlin.Array<DirectionsNearestWaypoints>? = null
) 



