/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* OpenAPI spec version: 1.0.1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package locationiq.models

import locationiq.models.Address
import locationiq.models.Namedetails

/**
 * 
 * @param placeId 
 * @param licence 
 * @param osmType 
 * @param osmId 
 * @param boundingbox 
 * @param lat 
 * @param lon 
 * @param displayName 
 * @param propertyClass 
 * @param type 
 * @param importance 
 * @param address 
 * @param namedetails 
 */
data class Location (
    val placeId: kotlin.String? = null,
    val licence: kotlin.String? = null,
    val osmType: kotlin.String? = null,
    val osmId: kotlin.String? = null,
    val boundingbox: kotlin.Array<kotlin.String>? = null,
    val lat: kotlin.String? = null,
    val lon: kotlin.String? = null,
    val displayName: kotlin.String? = null,
    val propertyClass: kotlin.String? = null,
    val type: kotlin.String? = null,
    val importance: java.math.BigDecimal? = null,
    val address: Address? = null,
    val namedetails: Namedetails? = null
) {

}

