/**
* LocationIQ
* LocationIQ provides flexible enterprise-grade location based solutions. We work with developers, startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of the technical aspects of our API and will help you get started.
*
* The version of the OpenAPI document: 1.1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package locationiq.models

import locationiq.models.Address
import locationiq.models.Matchquality
import locationiq.models.Namedetails

import com.squareup.moshi.Json
/**
 * 
 * @param distance 
 * @param placeId 
 * @param licence 
 * @param osmType 
 * @param osmId 
 * @param boundingbox 
 * @param lat 
 * @param lon 
 * @param displayName 
 * @param propertyClass 
 * @param type 
 * @param importance 
 * @param address 
 * @param namedetails 
 * @param matchquality 
 */

data class Location (
    @Json(name = "distance")
    val distance: java.math.BigDecimal? = null,
    @Json(name = "place_id")
    val placeId: kotlin.String? = null,
    @Json(name = "licence")
    val licence: kotlin.String? = null,
    @Json(name = "osm_type")
    val osmType: kotlin.String? = null,
    @Json(name = "osm_id")
    val osmId: kotlin.String? = null,
    @Json(name = "boundingbox")
    val boundingbox: kotlin.Array<kotlin.String>? = null,
    @Json(name = "lat")
    val lat: kotlin.String? = null,
    @Json(name = "lon")
    val lon: kotlin.String? = null,
    @Json(name = "display_name")
    val displayName: kotlin.String? = null,
    @Json(name = "class")
    val propertyClass: kotlin.String? = null,
    @Json(name = "type")
    val type: kotlin.String? = null,
    @Json(name = "importance")
    val importance: java.math.BigDecimal? = null,
    @Json(name = "address")
    val address: Address? = null,
    @Json(name = "namedetails")
    val namedetails: Namedetails? = null,
    @Json(name = "matchquality")
    val matchquality: Matchquality? = null
) 



